[config]
"Secrets/Nithra/git-agecrypt.nix" = ["age13g0z6876570jnfmf3qjrcmmgtsg7eyvp48k5aw9g2vlfptaldujs2s3zgg"]
"Secrets/Maldoria/git-agecrypt.nix" = ["age13g0z6876570jnfmf3qjrcmmgtsg7eyvp48k5aw9g2vlfptaldujs2s3zgg"]
